DROP TABLE person_permission IF EXISTS;
DROP TABLE person IF EXISTS;
DROP TABLE permission IF EXISTS;

CREATE TABLE person (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30),
  birth_date DATE,
  email      VARCHAR(100)
);
ALTER TABLE person ADD CONSTRAINT UC_Person UNIQUE (email);

CREATE TABLE permission (
  id         INTEGER PRIMARY KEY,
  name       VARCHAR(30) 
);

CREATE TABLE granted_permissions (
  person_id     INTEGER,
  permission_id INTEGER,
  granted       DATE,
  PRIMARY KEY (person_id, permission_id),
  FOREIGN KEY (person_id) REFERENCES person(id),
  FOREIGN KEY (permission_id) REFERENCES permission(id)
);